### ISSUE TITLE
Blog about steps taken to modernize a government website 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/blog-nrrd#182]

**Comment by Maroyafaied** [comment]
I started a draft/outline https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Blog/In%20Progress/Process%20of%20redesigning%20onrr.gov.docx?d=wf9169c21e9384262a3311609476b339c&csf=1&web=1&e=Nl0rSt

**Comment by cthomasONRR** [comment]
@Maroyafaied I put all the info I can think of in the blog doc. I tried to keep your existing structure, but did add in a few subsections. Feel free to edit away- no need for track changes. I just wanted to help get thoughts down. I used the responses we developed for Dawn at GSA when possible.

Sections "launch of beta site" and "implementation of search.gov" are the only areas where I didn't know much technical detail to contribute, so those still need content added. Everything else will hopefully be editing and adding small amounts of new content.

I think this will be a great "capstone" blog post that touches on so many other blog posts during the redesign!

**Comment by lpgoldstein** [comment]
@cthomasONRR @Maroyafaied I made light edits. I think it reads as complete. Implementation of search.gov seems like it's own blog post.

**Comment by Maroyafaied** [comment]
@cthomasONRR @lpgoldstein I've added a bit more for technical information, I think this close to being finalized but I'd like to read it one more later this week.  I might also get Shannon's input to see if we missed any major aspects of the redesign process.

**Comment by cthomasONRR** [comment]
@Maroyafaied I made some minor edits to your text additions. I kept them all in track changes.

**Comment by lpgoldstein** [comment]
@Maroyafaied also made a few edits and track changes are on.

**Comment by Maroyafaied** [comment]
Here's a doc with Shannon's comments / input https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Blog/In%20Progress/Process%20of%20redesigning%20onrr.gov%20-%20Shannon%27s%20comments.docx?d=wff0bc8bac7004177b1e7efa39fbf8832&csf=1&web=1&e=72lx8L

**Comment by Maroyafaied** [comment]
@lpgoldstein @cthomasONRR I responded to all the comments. I'll move this to next sprint since Christine is out to review one final time.

**Comment by cthomasONRR** [comment]
@Maroyafaied @lpgoldstein I responded to Maroya's comments about the blog title and the new intern section. I also cleaned up the doc. Unless anyone wants to edit/change my additions, I think this blog is ready for PR and markdown!

**Comment by lpgoldstein** [comment]
@Maroyafaied @cthomasONRR I've been going in and making little edits too. I can get the PR ready?

**Comment by Maroyafaied** [comment]
@cthomasONRR @lpgoldstein Thanks, I replied to a comment about Alex who was a fed employee through open opps not an intern through vsfs. @lpgoldstein go ahead an put it in markdown and you can create a PR after the plain language blog is released.

**Comment by cthomasONRR** [comment]
@lpgoldstein Are you ok closing this issue now?
