### ISSUE TITLE
blog USWDS design principles

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/blog-nrrd#196]
Refine the [USWDS write up](https://doimspp-my.sharepoint.com/:w:/g/personal/elzie_mms_gov/EYUYvjY5MqRCrlemQ-q2nf0BbGrlTNLUv0E8Ip-sDlqafQ?e=ucKgnu) and add blog post

**Comment by eelzi-ONRR** [comment]
@Maroyafaied @lpgoldstein  @cthomasONRR  I've made a few minor changes to add more hyperlinked text and bring the reading level down to grade 10. It ready for review if/when you have time.

https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Blog/In%20Progress/USWDS%20write-up.docx?d=w9a4c33d5f7b143c3b5db2ef4a2b21950&csf=1&web=1&e=sNVfRT

**Comment by lpgoldstein** [comment]
@eelzi-ONRR added comments within document. Looks great! Always so helpful to synthesize our efforts and pull out new ways to improve. Helpful to have fresh eyes on us as well.

**Comment by cthomasONRR** [comment]
@eelzi-ONRR I finished my review- I added some clarification text in track changes and some comments with mainly hyperlinks you can add in. Let me know if you have any questions about putting the doc in Markdown. Looks great, thanks!

**Comment by eelzi-ONRR** [comment]
@lpgoldstein @cthomasONRR Thank you both so much for your feedback. I've made changes and corrections accordingly. 

I should be okay with Markdown (I had to use it for the NRRD page we added last week) but I'll let you know if I need help - thanks for the offer!

**Comment by eelzi-ONRR** [comment]
Blog is revised and in markdown. Closing this issue sine we're not ready to post it yet due to the migration to the DOI github
