### ISSUE TITLE
Blog analytics

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/blog-nrrd#209]

**Comment by cthomasONRR** [comment]
@lpgoldstein The Jan 23 blog analytics are ready for your review:
https://github.com/DOI-ONRR/blog-nrrd/wiki/Analytics

Spreadsheet here (note: be sure to not click anything in the spreadsheet, I had some weird cells that did not match my back-up sheet this month).
https://doimspp.sharepoint.com/:x:/r/sites/NRRD/_layouts/15/Doc.aspx?sourcedoc=%7B480D1A94-EAD7-47BF-9841-64D5D1C1A981%7D&file=Blog_Analytics.xlsx&action=default&mobileredirect=true

**Comment by lpgoldstein** [comment]
@cthomasONRR looks great. I also didn't click on anything in the spreadsheet. I do need to add the blog to our quarterly metrics as well.
