### ISSUE TITLE
Draft plain language blog post

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/blog-nrrd#210]

**Comment by cthomasONRR** [comment]
@eelzi-ONRR @AlexandracmONRR @lpgoldstein @Maroyafaied 

This first draft is ready for review and can be found here; https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Blog/In%20Progress/plain%20language%20on%20onrr.gov.docx?d=wcb27cb5231bf4128a92dec9e0905daf9&csf=1&web=1&e=Sd3gBJ

This post is about coordinating with SMEs and rewriting in plain language. I couldn't talk about plain language without going through our coordination process with the SMEs. 

I have some questions/thoughts already in the comments for feedback. 

I also went though and reduced reading levels for each section as much as I could (reading levels in red type).

The images make the document long, but you can open the navigation pane to jump around easier.

**Comment by AlexandracmONRR** [comment]
This article is great! My edits are in tracked changes and I have left a few comments for your consideration. 

Let me know if you have any questions or comments on my feedback.

Best,
Alex

**Comment by lpgoldstein** [comment]
@cthomasONRR love the post. It will be a great reference for us the next time we need to go through the process or share with colleagues and interns who are interested in doing something similar. Everyone should know how to do this.

**Comment by eelzi-ONRR** [comment]
@cthomasONRR This is so good! I made a couple minor suggestions, but I also think it's great as is!

**Comment by Maroyafaied** [comment]
@cthomasONRR Great blog! I left two minor comments/suggestions.

**Comment by cthomasONRR** [comment]
I have everyone's comments/suggestions incorporated. This is ready to publish after USWDS blog :) Thanks for everyone's help!
