### ISSUE TITLE
Blog on Isabel's internship experience 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/blog-nrrd#224]

**Comment by Isabelh99** [comment]
@eelzi-ONRR 
Hi Erin! I got done a little earlier. :)
Below are some ideas and rough outlines to do the blog on. This is my first take on it and I think you might have more info/further details from behind-the-scenes. Or maybe know more on what we can / can't share. Anyway, feel free to comment or provide any feedback!

Note: _Suggested Illustrations_ mentioned in the outline below
I think some suggested illustrations below can be too large (i.e miro affinity map or axure designs) to place into the blog and it might be helpful if we just zoom over specified content or so. 

Title ideas / variations:
- A Ux Study on Pricing Filters
- Pricing Filters User Research on the New ONRR Website*
*might reduce title length :)

Below is a **rough outline**:
0. Intro
    - About 
   
1. Planning
    a. crafting a ux study document
          - defining scope & purpose
              - communication from users about a potential filter issue
          - assessing user types
          - simplicity element, etc.
     b. *suggested illustration: completed word doc*

2. Conducting the Study
     a. assessing potential contacts available for interview
     b. prepping a shared spreadsheet(s)
           - a sign up spreadsheet for notetakers and observers on pricing table user research sessions [https://docs.google.com/spreadsheets/d/1AadVBLoyuDThwfTgujAmK4iiK6uwm7YQDrfA--_qEl4/edit#gid=0](url)
           - a spreadsheet housing ux research [https://docs.google.com/spreadsheets/d/15xrc08le5mYEllWOoRQQV2o9L6-0xNPXGK5bcI25Zbo/edit#gid=2073073030](url)
     c. conducting calls with interviewee and notetakers
     d. regroup
           - Miro: affinity mapping
                *suggested illustration* completed map 
           - Other commentary (i.e: onrr team interaction ability or cover other parts of the spreadsheet)
        
3. Prototyping
     a. Walking thorough the [shaping process](https://github.com/DOI-ONRR/nrrd/wiki/Shaping-Process)  
     b. Presentation of prototypes to developer
            - notes on feedback from presentation on prototypes
            - *suggested illustrations: pencil sketches*
     c. Demonstrating tentative prototypes on Axure / basic design software
            - *suggested illustrations: axure designs* [https://4ja5jh.axshare.com/?id=awambs](url)
         
5. Lessons Learned 
    a. mistakes
    b. opportunities
    c. recommendations, etc.

6. Conclusion
