### ISSUE TITLE
Blog on Matt's internship experience

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/blog-nrrd#225]

**Comment by Maroyafaied** [comment]
@Baymatt I'm moving this issue for next sprint, please let me know if you need help or if you have a draft ready for review. Thanks

**Comment by Maroyafaied** [comment]
@Baymatt any updates on the blog?

**Comment by Baymatt** [comment]
@Maroyafaied I've mainly been working on a project for school that's due this coming Monday, so not much progress has been made on the blog post. When you're able to, can you or Lindsay send me some questions to answer for the blog? I'm planning to write about my own experiences as well as answering some questions, or at the very least, using the questions as a starting off point for some areas.

**Comment by Maroyafaied** [comment]
@Baymatt thanks for the update. @lpgoldstein will send you questions.

**Comment by Maroyafaied** [comment]
@lpgoldstein I was wrong about grammerly writing blogs. @baymatt Lindsay put your answers in chatgpt and it generated a nice draft for your blog. I'm attaching the link to the file so you can make review/edits. I think it would be nice to add a conclusion paragraph talking about the followship or future plans.  Thanks!

https://doimspp.sharepoint.com/:w:/s/NRRD/ES7b4Ri5k0ROmbGEI-Doc-8BMn7i4SXghN58TJgK3DiVrQ?email=Maroya.Faied%40onrr.gov&e=4%3AQhIeSD&CID=c5694c7a-690f-d53d-2770-055a5f584211

**Comment by lpgoldstein** [comment]
Closing. Will be published in July.
