### ISSUE TITLE
Blog on content audit/inventory - Outline and start draft

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/blog-nrrd#227]
@cthomasONRR not sure if you wanted to start this blog this sprint? I had it in the sprint goals so I made an issue.

**Comment by cthomasONRR** [comment]
@Maroyafaied I have an outline drafted. If you have time to review that would be great! 
https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Blog/In%20Progress/Content%20Audit%20Blog.docx?d=wa128246f3aa04a11a2221144e60cf775&csf=1&web=1&e=leUatw

**Comment by Maroyafaied** [comment]
@cthomasONRR This outline is awesome, I have no changes. Just made one comment. Thanks
