### ISSUE TITLE
Blog on Trusted Tester process

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/blog-nrrd#240]
Include what testing was like, problems accessing ANDI and how Maroya solved it, etc.

**Comment by Maroyafaied** [comment]
testing slack feed

**Comment by eelzi-ONRR** [comment]
Outline: https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Blog/In%20Progress/Trusted%20Tester%20outline.docx?d=w6ba449b0f9bf42669293e50f4dc66bb9&csf=1&web=1&e=XDGwDY
Blog draft: https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Blog/In%20Progress/Trusted%20Tester.docx?d=w1bf8f3b407624fd3b7871b46bb033ffd&csf=1&web=1&e=XWh2XK

**Comment by Maroyafaied** [comment]
@eelzi-ONRR @lpgoldstein I've added my portion and included an image. I'll try to save that image in the shared folder to have it for the PR. Feel free to make edits.

**Comment by Maroyafaied** [comment]
image is saved here. https://doimspp.sharepoint.com/:i:/r/sites/NRRD/Shared%20Documents/General/Blog/In%20Progress/ANDI.PNG?csf=1&web=1&e=qVUElk

**Comment by lpgoldstein** [comment]
@cthomasONRR do you have time to review the blog? https://doimspp.sharepoint.com/:w:/r/sites/NRRD/_layouts/15/Doc.aspx?sourcedoc=%7B1BF8F3B4-0762-4FD3-B787-1B46BB033FFD%7D&file=Trusted%20Tester.docx&nav=eyJjIjo3MDMwNzY1NzN9&action=default&mobileredirect=true

**Comment by cthomasONRR** [comment]
@lpgoldstein @eelzi-ONRR I reviewed and added comments. Overall it's very good- congrats!
