### ISSUE TITLE
Continue writing content audit blog

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/blog-nrrd#266]

**Comment by cthomasONRR** [comment]
@Maroyafaied The first draft is ready for your review. This is image heavy, as I thought showing the database would be more useful than lots of writing about it. Let me know what you think- I'm open to suggestions.

https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Blog/In%20Progress/Content%20Audit%20Blog.docx?d=w81b8817363294494b83e52d7f8924a15&csf=1&web=1&e=bivDn7

**Comment by Maroyafaied** [comment]
@cthomasONRR I left a few comments/suggestions. I think it's a great blog overall, awesome job!

**Comment by eelzi-ONRR** [comment]
@cthomasONRR Overall this is really great! I especially like that you talk about keeping motivated and keeping management engaged.

I made some minor suggestions in the doc

**Comment by cthomasONRR** [comment]
@Maroyafaied @eelzi-ONRR Thank you both for reviewing! I accepted all changes. For the title, are yall ok with "Creating a functional inventory database for website content audits" ?

**Comment by eelzi-ONRR** [comment]
@cthomasONRR That title sounds good to me!

**Comment by Maroyafaied** [comment]
@cthomasONRR The title sounds good. Thanks!

**Comment by cthomasONRR** [comment]
@Maroyafaied @eelzi-ONRR Thanks! I'll close this issue and open another one for next sprint to get the blog in a PR. Thanks again for all the input, I really appreciate it!
