### ISSUE TITLE
Draft & publish agile management blog 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/blog-nrrd#280]

**Comment by Maroyafaied** [comment]
@AlexandracmONRR @cthomasONRR @eelzi-ONRR @lpgoldstein @greensomes please feel free to review and give input on my blog draft. https://doimspp.sharepoint.com/:w:/r/sites/NRRD/_layouts/15/Doc.aspx?sourcedoc=%7B7adf1519-03b6-40ef-b5ce-b08d43f7a2b1%7D&action=edit&wdPid=1eee8b21

**Comment by cthomasONRR** [comment]
@Maroyafaied I completed my review. Looks great!

**Comment by lpgoldstein** [comment]
@Maroyafaied also reviewed. Had two tiny edits/comments. You make it sound so easy!
