### ISSUE TITLE
Outline Metrics/high-level goals blog

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/blog-nrrd#285]

**Comment by lpgoldstein** [comment]
@Maroyafaied Ready for your input: https://doimspp.sharepoint.com/:w:/s/NRRD/ESVOtYtyU8JBnYi_gnKhFhUBI8DsYDr-PxFWpD-jRygQDw?email=Maroya.Faied%40onrr.gov&e=pmAbee
