### ISSUE TITLE
Draft metrics/high level goals blog 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/blog-nrrd#288]

**Comment by Maroyafaied** [comment]
@lpgoldstein I drafted my sections , I haven't read through it yet but feel free to add your sections here https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Blog/In%20Progress/metrics%20blog.docx?d=wd52fbdce62b844a0a0331b6ea6fdc9b4&csf=1&web=1&e=MX2RbR

**Comment by Maroyafaied** [comment]
@cthomasONRR @eelzi-ONRR please review the drafted blog when you have time. Thanks https://doimspp.sharepoint.com/:w:/r/sites/NRRD/_layouts/15/Doc.aspx?sourcedoc=%7BD52FBDCE-62B8-44A0-A033-1B6EA6FDC9B4%7D&file=metrics%20blog.docx&action=default&mobileredirect=true&DefaultItemOpen=1&login_hint=faiedm%40mms.gov&ct=1703191871091&wdOrigin=OFFICECOM-WEB.START.EDGEWORTH&cid=768e56ce-d9c0-4b7e-8924-dbeacdecb9fa&wdPreviousSessionSrc=HarmonyWeb&wdPreviousSession=bf46878a-d386-4cde-b9d7-fa02ab0aef5b

**Comment by cthomasONRR** [comment]
@Maroyafaied Could you share the folder location? The link is trying to sign me in as you - never seen a sharepoint link do that before.

**Comment by Maroyafaied** [comment]
@cthomasONRR <img width="885" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0YvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b58719ee6c29131955457fdbdeaf41563996768b/image.png" alt="image.png" />

**Comment by eelzi-ONRR** [comment]
@Maroyafaied Done reviewing. I had a few minor typo corrections and some comments

**Comment by cthomasONRR** [comment]
@Maroyafaied I'm done reviewing. Looks great!

**Comment by lpgoldstein** [comment]
@Maroyafaied I incorporated Erin's comments and rebuilt
