### ISSUE TITLE
Start drafting blog on ONRR content audit/SME coordination

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/blog-nrrd#297]

**Comment by cthomasONRR** [comment]
@Maroyafaied I have the outline for my blog [here](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Blog/In%20Progress/ONRR-content-database_outline.docx?d=wa05b53c59592452dad31324c90e214bb&csf=1&web=1&e=dvAx9X).

If you have time, could you review? If not we can discuss at check-in Tuesday. Thanks!

**Comment by Maroyafaied** [comment]
@cthomasONRR Looks great, I left a couple of comments. Let me know if you have any questions. Thanks

**Comment by Maroyafaied** [comment]
@cthomasONRR I'm done reviewing, sorry for the delay. Great job, I enjoyed it! I suggested a few edits, I recommend having a different set of eyes to review before sending the PR preview link to the communication team.

**Comment by cthomasONRR** [comment]
@Maroyafaied  Thanks, I set up issue #300 to address reviews and set up the PR next sprint.
