### ISSUE TITLE
Blog reviews, set up PR, and comms approval

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/blog-nrrd#300]

**Comment by cthomasONRR** [comment]
@lpgoldstein 

I incorporated all of Maroya's edits into my blog. If you have time, could you please also review? Things I need help with are the title (I put everything in gpt but I didn't like any of its suggestions) and seeing if anything could upset comms approvals.

https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Blog/In%20Progress/ONRR-content-database_blog.docx?d=w6249943bc46c46c78b04c2b5fcddfaf9&csf=1&web=1&e=P6kUnH

**Comment by lpgoldstein** [comment]
@cthomasONRR of course! Will review this afternoon.
