### ISSUE TITLE
Look into blog analytics DAP code

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/blog-nrrd#305]
For January 2024, I'm seeing some unusual results in the blog analytics. I've never seen this in pervious months, and I'd like to make sure it doesn't have to the with DAP code and setting up our private account.

For Blog page referrers, I'm seeing several hundred of these referrer types. The referrers are usually like google or digital.gov, not these random strings.:
<img width="877" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2tyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b8eae1175608dc9030ef36ceb6fd804be873f83/image.png" alt="image.png" />

Also for blog referrers, I'm getting landing pages as really odd URLs for the individual blog posts:
<img width="1189" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3NyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f9ad1aed6efc9d0f5257cd14de82e196a05efaeb/image.png" alt="image.png" />

**Comment by greensomes** [comment]
@cthomasONRR, can you confirm that this still needs to be looked into?

**Comment by cthomasONRR** [comment]
@greensomes I just checked for February so far, and I don't see this issue for February. I went back to January and still see the issue there, but it doesn't seem to be in the February data.

**Comment by cthomasONRR** [comment]
@greensomes I guess we can close this, and I can reopen if I see it again.

**Comment by greensomes** [comment]
Ok, thanks!
