### ISSUE TITLE
Add accessibility statement and public feedback mechanism

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/blog-nrrd#306]
From Sid:

Per OMB Memorandum M-24-08, agencies are required to:
By March 20, 2024,
•	agencies shall establish (or review and update, as appropriate) digital accessibility statements on all agency websites.  
•	agencies shall establish (or review and update, as appropriate) a public feedback mechanism for receiving complaints or reports about accessibility issues with agency websites and digital services and begin to track, review, and address feedback.
Per GSA’s Government-wide IT Accessibility Program, DOI can establish and maintain a single accessibility statement webpage for all components to point to (such as the Department’s accessibility statement), or each agency can have a statement for each enterprise website. For additional guidance, please see Developing a Website Accessibility Statement.

By Friday, March 8, 2024, please provide confirmation by completing the attached spreadsheet (columns G and H) that your bureau/office has completed this requirement for your websites. Please let me know if you have any questions.

The spreadsheet indicates we need both a statement and instructions on a public feedback mechanism. The blog is listed in the sheet as one of ONRR's public-facing sites

**Comment by cthomasONRR** [comment]
Blog accessibility statement is live!
