### ISSUE TITLE
Write GA4 blog

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/blog-nrrd#316]
We got the online done, this issue is to finish writing

**Comment by cthomasONRR** [comment]
@lpgoldstein Do you have time to review our draft before I put it in a PR? It's located [here](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Blog/In%20Progress/GA4-transition.docx?d=wa1070c2caaf84183a340bc87fd9f6efc&csf=1&web=1&e=ccvudp)

**Comment by lpgoldstein** [comment]
@cthomasONRR reviewed - I only had two tiny grammar edits that you'll see in track changes.
