### ISSUE TITLE
Redo blog tags to align with digital.gov resource topics

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/blog-nrrd#359]
https://digital.gov/resources/

**Comment by eelzi-ONRR** [comment]
Wait for User Study 01 recommendations

**Comment by lpgoldstein** [comment]
USWDS considering implementing an interactive, accessible tagging component that could be a good way to start USWDSing the blog. After remap tags, we'll be ready to go when the USWDS component is ready.

Also we should be able to export the tags and run scripts to change them once we decide on the remapping

**Comment by cthomasONRR** [comment]
Create a Visual Basic script to allow multiple select of tags per blog
https://www.ablebits.com/office-addins-blog/create-multi-select-dropdown-excel/

**Comment by cthomasONRR** [comment]
Formal to count the number of occurrences of a text string in a Range
https://learn.microsoft.com/en-us/office/troubleshoot/excel/formulas-to-count-occurrences-in-excel

**Comment by lpgoldstein** [comment]
@cthomasONRR I've finished with my part. Want to meet Friday or Tuesday to categorize blogs? If not, we can always change name of issue to "catalog blog tags" and close it out.
