### ISSUE TITLE
Review M-23-22 self assessment blog

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/blog-nrrd#366]
Link to[ draft of M2322 self assessment blog](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Blog/In%20Progress/m-23-22.docx?d=wadac2b2913d14b7b96613b75cab2c317&csf=1&web=1&e=GV1MfB)

**Comment by AlexandracmONRR** [comment]
@cthomasONRR - I've added you to this issue to review the blog. Feel free to fit this in whenever it works for you. Thank you!

**Comment by cthomasONRR** [comment]
@AlexandracmONRR @lpgoldstein I reviewed and left comments. Overall great job :)
