### ISSUE TITLE
Review state and offshore region navigation page blog

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/blog-nrrd#369]
[Link to blog draft](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Blog/In%20Progress/[StateNavPage.docx](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Blog/In%20Progress/StateNavPage.docx?d=we5c505b1c1d84181bc19b4edecb1a4cc&csf=1&web=1&e=i9oEiz)?d=we5c505b1c1d84181bc19b4edecb1a4cc&csf=1&web=1&e=i9oEiz)

**Comment by eelzi-ONRR** [comment]
@AlexandracmONRR Finished reviewing and left comments. Overall I think it's a great start, it just needs to tightening up in the writing
