### ISSUE TITLE
Update metadescription to say ONRR/ODDD instead of DOI

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/blog-nrrd#372]
Recommendation from study 01. 

Metadescription will show in RSS aggregators

**Comment by AlexandracmONRR** [comment]
Jeff will point Christine into the correct direction on the code. Semi-related to issue #373

**Comment by cthomasONRR** [comment]
@lpgoldstein want to review?
https://dev-blog-nrrd.app.cloud.gov/

**Comment by lpgoldstein** [comment]
@cthomasONRR looks good!

**Comment by cthomasONRR** [comment]
This will go live when the next blog is published. Closing issue.
