### ISSUE TITLE
Add RSS link and icon

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/blog-nrrd#375]
We already have the code set up for this - we just need to design the link and location.

Ideally this will eventually go at both top and bottom of page, But we can easily add to the footer now and add to the top later with other design changes.

Recommendation from study 01.

**Comment by eelzi-ONRR** [comment]
Related to issue 360

**Comment by AlexandracmONRR** [comment]
included in prototypes tested on 8/30
