### ISSUE TITLE
Create about page content

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/blog-nrrd#377]
Explain who we are, that we're part of DOI, and the general subject matter of the blog. 

And maybe our typical post frequency since that came up a few times in the study?

Recommendation from study 01

**Comment by cthomasONRR** [comment]
@lpgoldstein Content for the new about page it ready for your review. Document [here](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Blog/Content/AboutUs_Content.docx?d=w8e75df2eb1734bbaa7e1df4549ac6e86&csf=1&web=1&e=bx9oUQ)

**Comment by lpgoldstein** [comment]
@cthomasONRR looks great! Thank you for doing this.

**Comment by cthomasONRR** [comment]
To add about page, Jeff says it's going to be a bit of a lift. I'll create a separate issue for Jeff.

- Change Gatsby configuration
- Figure out what this change needs to be
- Jeff will figure this out, and let Christine know so she can implement
