### ISSUE TITLE
Update blog writing wiki/add communications checklist

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/blog-nrrd#378]
Update https://github.com/DOI-ONRR/blog-nrrd/wiki/Blog-writing-for-new-authors
Add some of the opportunities from study 01
Add communications checklist (getting approval from Chris & OCO, where to send new blog post alerts, check the RSS feed worked properly, etc.)

Recommendation from study 01

**Comment by AlexandracmONRR** [comment]
@cthomasONRR and @lpgoldstein - would either of you have time to review the addition to the blog wiki?

Opportunities from study 01 

- "Continue writing thoughtful summaries and title with different types of users in mind (readers vs. scanners)" https://github.com/DOI-ONRR/blog-nrrd/wiki/Publishing-a-blog-post-(a-to-z)#about-the-excerpt
- other opportunities are already included in the wiki page

Communications Checklist: 
https://github.com/DOI-ONRR/blog-nrrd/wiki/Publishing-a-blog-post-(a-to-z)#distributing-blog-post

**Comment by lpgoldstein** [comment]
@alexandracmonrr I just made a formatting change. Thanks for doing this. @cthomasONRR and I will update again once we have the blog tagging system figured out.

**Comment by cthomasONRR** [comment]
@AlexandracmONRR I also made minor formatting changes but didn't touch the content. Looks good.

**Comment by AlexandracmONRR** [comment]
@lpgoldstein and @cthomasONRR - thank you for your review!

Agreed it will need an update once we do more with the tagging system and once we have established the notification system (RSS and/or subscription).
