### ISSUE TITLE
Write federal sales design studio blog

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/blog-nrrd#381]

**Comment by AlexandracmONRR** [comment]
[blog draft](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Blog/In%20Progress/Sales%20Data%20design%20studios.docx?d=w5b24ab9ca24443c6a6e23d72e2ea2210&csf=1&web=1&e=bUF2Rk)
