### ISSUE TITLE
Write blog about manual accessibility testing checklist & translating testing requirements into plain language

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/blog-nrrd#382]
For documents and interaction with document owners: https://github.com/DOI-ONRR/onrr.gov-site/wiki/Accessibility-guidance#manual-accessibility-testing-of-documents-checklist
and for ACRT, spreadsheet [here](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/Accessibility/2024_ACRT_Instructions.xlsx?d=w8b13bcaff0964982a0c8c0404b8d05e9&csf=1&web=1&e=WehZUs).

**Comment by cthomasONRR** [comment]
@lpgoldstein If you have time, could you please review?

[blog here](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Blog/In%20Progress/PlainLanguageAccessibilityInstructions.docx?d=w3a4b67b7bd2b48919e012d89eda1f47b&csf=1&web=1&e=xgo48p)

**Comment by AlexandracmONRR** [comment]
@cthomasONRR - this blog is great! I added some comments and tracked changes. I hope my feedback helpful!

**Comment by cthomasONRR** [comment]
@AlexandracmONRR @lpgoldstein Thanks for your feedback! I have all comments addressed. I made a new issue for cleaning it up and next steps for next sprint.
