### ISSUE TITLE
Put M-23-22 self assessment blog into dev and get review

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/blog-nrrd#385]
- [x] 1. Put blog into dev
- [x] 2. Send to Haley for review
- [x] 3. Send to Chris for review

**Comment by AlexandracmONRR** [comment]
[Preview](https://dev-blog-nrrd.app.cloud.gov/m-23-22-self-assessment/)
[Word doc](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Blog/In%20Progress/M-23-22-blogdraft.docx?d=w634504e72d614b7ea499eb5a138d5ceb&csf=1&web=1&e=14wQLu)

@eelzi-ONRR would you be able to review this blog?

**Comment by eelzi-ONRR** [comment]
@AlexandracmONRR I'm finished reviewing. It's good but a lot of info! I made suggestions in the word doc for some simplifications and removing passive tense

**Comment by AlexandracmONRR** [comment]
@lpgoldstein - sent to haley on 7/31

**Comment by lpgoldstein** [comment]
@AlexandracmONRR 
![image](https://github.com/user-attachments/assets/22a86bcc-8cf5-432e-a540-ab047a004627)

**Comment by lpgoldstein** [comment]
@AlexandracmONRR no other updates.

**Comment by lpgoldstein** [comment]
@AlexandracmONRR approved by Chris!
