### ISSUE TITLE
Review draft of federal sales data blog draft

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/blog-nrrd#389]
[Federal Sales blog draft](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Blog/In%20Progress/Federal%20Sales%20Data%20-%20Blog%20Draft.docx?d=w3d9be546aa244fd68662454a2637e059&csf=1&web=1&e=hIFfBB)

**Comment by lpgoldstein** [comment]
@AlexandracmONRR provided feedback as well. Happy to discuss. Great start!

**Comment by AlexandracmONRR** [comment]
After I incorporate edits, send tracked changes and clean version to erin

**Comment by lpgoldstein** [comment]
@AlexandracmONRR closing issue and then you can make another issue for cleanup.
