### ISSUE TITLE
Review state and offshore navigation blog post

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/blog-nrrd#396]
Just a heads up, I made some changes to the subtitles and layout related to the individual prototypes and "prototyping part one..." and "prototyping part two..." of user research. Please review these sections more closely, if possible.

[Preview of blog post](https://dev-blog-nrrd.app.cloud.gov/hallway-study-state-offshore-navigation/)

**Comment by lpgoldstein** [comment]
@cthomasONRR @AlexandracmONRR I pulled the [blog back into word](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Blog/In%20Progress/The%20beauty%20of%20hallway%20testing%20REVIEW.docx?d=wb9d870d45e924ca3a954ad2e5a28cfab&csf=1&web=1&e=dQTevP) to review. I've done a first pass but will review again tomorrow.

**Comment by cthomasONRR** [comment]
@AlexandracmONRR I also added edits to Lindsay's word doc. I only had a few minor things. Looks good.
