### ISSUE TITLE
Revisit blog title capitalization

### ISSUE THREAD

**Issue by ghost** [DOI-ONRR/blog-nrrd#98]
We need to change capitalization of some blog titles for consistency

**Comment by shannonmcharg** [comment]
I changed a bunch of them for consistency this morning.  Take a look at the preview in the PR for Meshan's post.

**Comment by mcharg** [comment]
@daniel-coleman-1 I somehow missed these two that you can fix later.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/22be4996-5232-4a18-b038-d43562c2cfcf)
